name: 'sys_dbt_ga4'
version: '1.0.0'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table

vars:
  enable_fivetran_ad_report_mapping: false
  enable_other_mapping: false
  # mapping_dataset: 
  # mapping_table: 
  # ad_reporting__ad_report: "{{ ref('ad_reporting__ad_report') }}"
